# Service for Envoy
apiVersion: v1
kind: Service
metadata:
  name: {{envoy_name}}
  namespace: {{namespace}}
  labels:
    app: {{envoy_name}}
spec:
  ports:
    - port: 80
      targetPort: 10000
      protocol: TCP
      name: http
    - port: 9901
      targetPort: 9901
      protocol: TCP
      name: admin
  selector:
    app: {{envoy_name}}
  type: {{service_type}}