services:
  postgres-db:
    image: postgres:17.4-alpine3.21
    container_name: pg
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypass"
      POSTGRES_DB: "mydb"
    volumes:
      - /home/docker/postgres/data:/var/lib/postgresql/data
      - /home/docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - /home/docker/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    restart: always
    depends_on:
      - postgres-db
    ports:
      - "6432:6432"
    environment:
      DB_USER: "myuser"
      DB_PASSWORD: "mypass"
    volumes:
      - /home/docker/pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - /home/docker/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt