# this is open-source from elasticsearch and kibana
services:
  # open-source like elasticsearch - this is forked from elasticsearch
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "plugins.security.disabled=true"  # Disable security for dev
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  ## open-source like kibana - this is forked from kibana
  dashboard:
    image: opensearchproject/opensearch-dashboards:2.12.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    ports:
      - "5601:5601"