plugins {
  id 'java-library' // import to use 'api' in dependencies
  id 'java'
  id 'org.springframework.boot' version '2.7.18'
  id 'io.spring.dependency-management' version '1.1.6'
  //------------------------------------------------
  id 'me.champeau.jmh' version '0.7.2'
  id 'jacoco'
  id 'maven-publish'
  id 'io.gatling.gradle' version '3.10.5'
  id "org.openapi.generator" version "7.8.0" // OpenAPI Generator
// use this then ./gradlew jib (push to registry) gradle -> image
  id 'com.google.cloud.tools.jib' version '3.4.0'
}

apply(from: "./gradle/profile-config.gradle")

group = 'org.app.common'
version = '2.0.0'

java.toolchain.languageVersion = JavaLanguageVersion.of(11)
jacoco.toolVersion = "0.8.10"

jar {
  enabled = true
  archiveFileName = "${group}${version}.jar"
}

// use when in spring project
bootJar {
  enabled = true
  layered {}
}

// normal way   : build -> jar -> docker file -> docker image
// with this way: build -> image
//bootBuildImage {
//  imageName = "registry.company.com/my-service:1.0"
//  builder = "buildpacks/builder-jammy-base"
//  environment = [
//    "BP_JVM_CDS_ENABLED": "true", // startup down 20–40%
//    "BP_JVM_VERSION": "21",
//    "BP_JVM_TYPE": "JRE"
//  ]
//  docker {
//    publishRegistry {
//      username = project.findProperty("dockerUser")
//      password = project.findProperty("dockerPass")
//    }
//  }
//}

//jib {
//  containerizingMode = 'packaged' // or exploded (build faster)
//
//  from {
//    image = 'eclipse-temurin:17-jre'
//  }
//
//  to {
//    image = System.getenv("IMAGE_NAME") // inject từ CI
//    auth {
//      username = System.getenv("REGISTRY_USER")
//      password = System.getenv("REGISTRY_PASS")
//    }
//  }
//
//  container {
//    jvmFlags = ['-Xms512m', '-Xmx512m']
//  }
//}

sourceSets.main {
  java.srcDir("src/main/java")
  resources.srcDirs("src/main/resources")
}

subprojects {
  apply plugin: 'java'
  apply plugin: 'java-library'
  apply plugin: 'org.springframework.boot'
  apply plugin: 'io.spring.dependency-management'

  dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'
    implementation logLibs.slf4j.api
  }

  dependencyManagement {
    imports {
//      mavenBom "org.springframework.boot:spring-boot-dependencies:2.7.18"
      mavenBom "org.springframework.cloud:spring-cloud-dependencies:2021.0.3"
    }
  }
}

// logging
dependencies {
  api(logLibs.bundles.logging)
}

// cache
dependencies {
  api cacheLibs.bundles.all
}

// test
dependencies {
  testImplementation(testLibs.bundles.all)
}

// high performance
dependencies {
  // 1. agrona: high performance data structures and utilities for low-latency applications
  // designed for high throughput and low latency, often used in financial applications
//  api 'org.agrona:agrona:1.17.0'
  // 2. disruptor: high-performance inter-thread messaging library
  // designed for low latency and high throughput, often used in real-time systems
//  api 'com.lmax:disruptor:3.4.4'
  // 3. HFT: high performance time series data store, microsecond latency message system that persists to disk
  // designed for low latency and high throughput use cases
//  api "net.openhft:chronicle-queue:5.27ea9"
  // 4. HPPC: High Performance Primitive Collections for Java
  // focuses on providing optimized collections for primitive types, aiming for the highest performance and memory efficiency
//  api "com.carrotsearch:hppc:0.10.0"
}

// tools
dependencies {
  annotationProcessor 'org.projectlombok:lombok:1.18.34'
  compileOnly 'org.projectlombok:lombok:1.18.34'

  api intergationLibs.bundles.grpc
  api intergationLibs.bundles.integration
  api platform(jsonLibs.jackson.bom)
  api jsonLibs.bundles.all
  api jsonLibs.bundles.jackson

  // 13. opencsv: CSV
//  api 'com.opencsv:opencsv:5.9'
  // 14. poi: Excel
//  api 'org.apache.poi:poi-ooxml:5.4.0'
  // 15. mantis
  // Low-latency, high-throughput data processing.
  // Auto-scaling stream processing jobs.
  // Monitor with Mantis UI or Metric
//  runtimeOnly 'io.mantisrx:mantis-runtime:3.1.11'
  // 18. lucene: for handler text, english, etc ...
  // api 'org.apache.lucene:lucene-analysis-common:10.1.0'
  // 21. google code
//  api 'com.google.guava:guava:33.4.8-jre'
  // 23. jasperreports
//  api 'net.sf.jasperreports:jasperreports:7.0.1'
  // 24. Yahoo / Clearspring
  api 'com.clearspring.analytics:stream:2.9.8'
  // 25. Apache DataSketches | best for case hardware analyze data than clearspring is lightweight
//  api 'org.apache.datasketches:datasketches-java:7.0.1'
  // 28 parquet
//  api 'org.apache.parquet:parquet-avro:1.15.2'
  // 29. hadoop
//  api 'org.apache.hadoop:hadoop-common:3.4.1'
  // 30. vertx
//  api 'io.vertx:vertx-web:4.5.1'
  // 33. crdt
//  api 'com.netopyr.wurmloch:wurmloch-crdt:0.1.0'
  // 35. Bytecode instrumentation (BCI) ASM (low-level, powerful)
//  api 'org.ow2.asm:asm:9.8'
  // 36. Bytecode instrumentation (BCI) Javassist (simpler API for modifying methods, adding fields)
//  api 'org.javassist:javassist:3.30.2-GA'
  // 39. auto-service
//  compileOnlyApi 'com.google.auto.service:auto-service-annotations:1.1.1'
//  annotationProcessor 'com.google.auto.service:auto-service:1.1.1'
  // 40. Apache Commons Net for FTP, SFTP, SMTP, etc.
  //  api 'commons-net:commons-net:3.9.0'
  // 41. Apache Commons Imaging to work with image files
  //  api 'org.apache.commons:commons-imaging:1.0-alpha2'
  // 42. Apache Commons Collections for advanced collection handling
//  api 'org.apache.commons:commons-collections4:4.5.0'
  // 43. Apache Commons Compress for handling compressed files
//  api 'org.apache.commons:commons-compress:1.26.0'
}

// spring boot
dependencies {
  api 'org.springframework.boot:spring-boot-starter-tomcat'
  api 'org.springframework.boot:spring-boot-starter'
  api 'org.springframework.boot:spring-boot-starter-actuator'
  api 'org.springframework.boot:spring-boot-starter-cache'
  api 'org.springframework.boot:spring-boot-starter-validation'
  api 'org.springframework.boot:spring-boot-starter-web'
  api 'org.springframework.boot:spring-boot-starter-aop'
  api 'org.springframework.boot:spring-boot-starter-data-redis'
  api 'org.springframework.boot:spring-boot-starter-data-jpa'
  api 'org.springframework.boot:spring-boot-starter-webflux'
//  api 'org.springframework.boot:spring-boot-starter-thymeleaf'
  api 'org.springframework.boot:spring-boot-starter-data-elasticsearch'
//  api 'org.springframework.boot:spring-boot-starter-jooq'
//  api 'org.springframework.boot:spring-boot-starter-mail'
//  api 'org.springframework.boot:spring-boot-starter-batch'
  api 'org.springframework.boot:spring-boot-starter-test'
  api 'org.springframework.boot:spring-boot-starter-graphql'
  api 'org.springframework.boot:spring-boot-starter-websocket'
  api("org.springframework.retry:spring-retry:2.0.12")

  // restart app to much time use this
//  developmentOnly 'org.springframework.boot:spring-boot-devtools'

  // ===================================================================
  // Spring documentation dependencies
  // ===================================================================
  api 'org.springdoc:springdoc-openapi-ui:1.8.0'
  api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'

  // ===================================================================
  // Spring data
  // ===================================================================
//  api 'org.springframework.boot:spring-boot-starter-data-couchbase'
  api 'org.springframework.boot:spring-boot-starter-data-cassandra'

  // ===================================================================
  // Spring cloud & monitor dependencies
  // ===================================================================
//  api 'org.springframework.cloud:spring-cloud-starter-openfeign'
  api 'org.springframework.cloud:spring-cloud-starter-config'
//  api 'org.springframework.cloud:spring-cloud-starter-vault-config'

  // should use 1 in 2: binder or kafka
//  api 'org.springframework.cloud:spring-cloud-stream'
//  api 'org.springframework.cloud:spring-cloud-stream-binder-kafka'
//  api 'org.springframework.cloud:spring-cloud-stream-binder-kafka-streams'

  api 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

  // version 2.7.x use this
  api 'org.springframework.cloud:spring-cloud-starter-sleuth'
  api 'org.springframework.cloud:spring-cloud-sleuth-zipkin'
  // version 3.0.x use this
  //    api 'io.zipkin.reporter2:zipkin-reporter-brave'
  //    api 'io.micrometer:micrometer-registry-prometheus'
  //    api group: 'io.micrometer', name: 'micrometer-tracing-bridge-brave', version: '1.3.3'


  // hystrix stop maintenance and not support spring boot 2.7+ so use resilience4j instead
  api 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'
//  api 'org.springframework.cloud:spring-cloud-starter-netflix-hystrix:2.2.10.RELEASE'
}

// alibaba cloud
dependencies {
  // 1. nacos-discovery better than eureka | nacos is a service discovery and configuration management platform
//  api 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery'
  // 2. nacos config better than spring config by manager all in 1 place is (NACOS SERVER)
//  api 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config'
}

// ===================================================================
// Import to dependency
// ===================================================================
dependencyManagement {
  imports {
    mavenBom "org.springframework.cloud:spring-cloud-dependencies:2021.0.3"
//    mavenBom "com.alibaba.cloud:spring-cloud-alibaba-dependencies:2021.0.4.0"
  }
}

openApiGenerate {
  generatorName.set("gatling")
  inputSpec.set("http://localhost:8080/v3/api-docs.yaml")
  outputDir.set("$buildDir/generated/gatling")
  apiPackage.set("org.app.common.controller")
}

// skip duplicate files in folder resource when build jar
processResources {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// Trong file .gradle (Groovy)
afterEvaluate {
  apply from: "./gradle/publishing.gradle.kts"
}
