# Service Account for CI/CD
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-service-account
  namespace: {{namespace}}
---
# Role for CI/CD
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd-role
  namespace: {{namespace}}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Role Binding for CI/CD
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd-role-binding
  namespace: {{namespace}}
subjects:
- kind: ServiceAccount
  name: cicd-service-account
  namespace: {{namespace}}
roleRef:
  kind: Role
  name: cicd-role
  apiGroup: rbac.authorization.k8s.io