package org.app.common.fluent;

import com.google.auto.service.AutoService;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Set;

@AutoService(Processor.class)
@SupportedAnnotationTypes("org.app.common.fluent.ChainSetter")
@SupportedSourceVersion(SourceVersion.RELEASE_8)
public class SimpleChainProcessor extends AbstractProcessor {

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (Element element : roundEnv.getElementsAnnotatedWith(ChainSetter.class)) {
            if (element.getKind() == ElementKind.CLASS) {
                try {
                    generateChainClass((TypeElement) element);
                } catch (IOException e) {
                    processingEnv.getMessager().printMessage(
                        javax.tools.Diagnostic.Kind.ERROR,
                        "Error: " + e.getMessage(), element);
                }
            }
        }
        return true;
    }

    private void generateChainClass(TypeElement classElement) throws IOException {
        ChainSetter annotation = classElement.getAnnotation(ChainSetter.class);
        String className = classElement.getSimpleName().toString();
        String packageName = processingEnv.getElementUtils().getPackageOf(classElement).toString();

        // Generate builder class
        String builderClassName = className + (annotation.lombok() ? "Chain" : "Builder");
        JavaFileObject builderFile = processingEnv.getFiler().createSourceFile(
            packageName + "." + builderClassName);

        try (PrintWriter writer = new PrintWriter(builderFile.openWriter())) {
            writeBuilderClass(writer, classElement, annotation, className, builderClassName, packageName);
        }
    }

    private void writeBuilderClass(PrintWriter writer, TypeElement classElement, ChainSetter annotation,
                                   String className, String builderClassName, String packageName) {
        writer.println("package " + packageName + ";");
        writer.println();
        writer.println("// Auto-generated by ChainSetter annotation processor");
        writer.println("public class " + builderClassName + " extends " + className + " {");
        writer.println();

        // Generate chaining methods for each field
        for (Element element : classElement.getEnclosedElements()) {
            if (element.getKind() == ElementKind.FIELD) {
                VariableElement field = (VariableElement) element;
                Set<Modifier> modifiers = field.getModifiers();

                if (!modifiers.contains(Modifier.STATIC) &&
                    !modifiers.contains(Modifier.FINAL)) {
                    generateChainMethod(writer, field, annotation, builderClassName);
                }
            }
        }

        // Add build method
        writer.println("    public " + className + " build() {");
        writer.println("        return this;");
        writer.println("    }");
        writer.println();

        writer.println("}");
    }

    private void generateChainMethod(PrintWriter writer, VariableElement field,
                                     ChainSetter annotation, String builderClassName) {
        String fieldName = field.getSimpleName().toString();
        String fieldType = field.asType().toString();
        String capitalizedName = capitalize(fieldName);

        String methodName;
        if (annotation.chain()) {
            methodName = "set" + capitalizedName;
        } else if (annotation.fluent()) {
            methodName = fieldName;
        } else {
            methodName = annotation.prefix() + capitalizedName;
        }

        writer.println("    public " + builderClassName + " " + methodName + "(" + fieldType + " " + fieldName + ") {");
        writer.println("        super.set" + capitalizedName + "(" + fieldName + ");");
        writer.println("        return this;");
        writer.println("    }");
        writer.println();
    }

    private String capitalize(String str) {
        if (str == null || str.isEmpty()) return str;
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }
}

