services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
#      VAULT_DEV_ROOT_TOKEN_ID: "vault-token"
#      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://0.0.0.0:8200"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/file
    healthcheck:
      test: ["CMD", "vault", "status"]
    cap_add:
      - IPC_LOCK
    command:
      - vault server -config=/vault/config/vault.hcl
#    entrypoint: vault server -dev -dev-listen-address="0.0.0.0:8200" -dev-root-token-id="root"