# 03-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{service-name}}-secrets
  namespace: {{namespace}}
type: Opaque
data:
  # Base64 encoded values
  DB_PASSWORD: {{base64-encoded-db-password}}
  API_KEY: {{base64-encoded-api-key}}