# 06-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{service-name}}-hpa
  namespace: {{namespace}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{service-name}}
  minReplicas: {{min-replicas}}
  maxReplicas: {{max-replicas}}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{cpu-utilization-percentage}}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{memory-utilization-percentage}}