apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{app-name}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{app-name}}
  template:
    metadata:
      labels:
        app: {{app-name}}
    spec:
      containers:
        - name: {{app-name}}
          image: {{app-name}}:latest
          ports:
            - containerPort: 8080