service:
  name: "user-service"
  port: 8080

image:
  repository: "your-group/user-service"
  tag: "v1.2.3"

# EASY SCALING - JUST CHANGE THESE NUMBERS
replicaCount: 5
autoscaling:
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60

# EASY RESOURCE CHANGES
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# SERVICE-SPECIFIC ENVIRONMENT
env:
  - name: DATABASE_URL
    value: "postgresql://user-db:5432/users"
  - name: CACHE_URL
    value: "redis://redis:6379"

ingress:
  hosts:
    - host: "user-api.yourdomain.com"
      paths:
        - path: /api/users
          pathType: Prefix