services:

  nexus:
    image: sonatype/nexus3
    volumes:
      - nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1200m -Xmx1200m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
    expose:
      - 8081
    ports:
      - "8381:8081"
    restart: always