# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.5.2

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: postgres18-pod
  name: postgres18-pod
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_USER
      value: admin
    - name: POSTGRES_DB
      value: postgres
    - name: POSTGRES_PASSWORD
      value: admin
    image: docker.io/library/postgres:18
    name: postgres18
    ports:
    - containerPort: 5432
      hostPort: 5434
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: postgres-postgres-data-pvc
  volumes:
  - name: postgres-postgres-data-pvc
    persistentVolumeClaim:
      claimName: postgres-postgres-data
