groups:
- name: SpringBootAlerts
  rules:
  - alert: HighCpuUsage
    expr: process_cpu_usage > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 80% for 5 minutes on {{ $labels.instance }}"

  - alert: HighMemoryUsage
    expr: sum(jvm_memory_used_bytes) / sum(jvm_memory_max_bytes) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is above 80% for 5 minutes on {{ $labels.instance }}"

  - alert: HighLatency
    expr: http_server_requests_seconds_max{status!~"5.."} > 1
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High latency detected"
      description: "HTTP request latency is above 1 second on {{ $labels.instance }} for {{ $labels.uri }}"

  - alert: HighErrorRate
    expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[1m])) / sum(rate(http_server_requests_seconds_count[1m])) > 0.05
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High error rate detected"
      description: "Error rate is above 5% for 1 minute on {{ $labels.instance }}"