stages:
  - build
  - deploy-staging
  - deploy-production

variables:
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  KUBE_NAMESPACE: production

# Build and Push Docker Image
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest

# Update ArgoCD Application
deploy-production:
  stage: deploy-production
  image: alpine/git:latest
  script:
    - apk add --no-cache curl
    # Update image tag in values file
    - sed -i "s|tag:.*|tag: \"$CI_COMMIT_SHA\"|g" services/$SERVICE_NAME/values.yaml
    - git config user.email "gitlab-ci@yourdomain.com"
    - git config user.name "GitLab CI"
    - git add services/$SERVICE_NAME/values.yaml
    - git commit -m "Update $SERVICE_NAME to $CI_COMMIT_SHA"
    - git push https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/your-group/k8s-config.git HEAD:main
  only:
    - main