services:

  # may be not good in community edition
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --requirepass (password)
      --bind 0.0.0.0
      --protected-mode no
    restart: always

  # Valkey is a Redis-compatible fork and it open-sources so it free
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    command: >
      valkey-server
      --requirepass (password)
      --bind 0.0.0.0
      --protected-mode no
    restart: always
