apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

namespace: monitoring-dev

labels:
  - pairs:
      environment: dev
    includeSelectors: true

patches:
  - path: elasticsearch-patch.yaml
  - path: skywalking-oap-patch.yaml
  - path: skywalking-ui-patch.yaml

configMapGenerator:
  - name: skywalking-config
    literals:
      - ENVIRONMENT=development